config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"

  # Lookbook has to be mounted before `get '/:locale'`, otherwise the router will treat 'lookbook' as a locale and throw an error
  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  # Brings the sole locale route to the homepage
  get "/:locale" => "home#index", :as => "locale_root"

  scope "(:locale)", locale: /en|de/ do
    devise_for :users,
      path: "users",
      path_names: {
        sign_in: "login",
        sign_out: "logout",
        sign_up: "register"
      },
      controllers: {
        sessions: "users/sessions",
        registrations: "users/registrations"
      }
    get "profile" => "profile#show", :as => "profile"

    resources :countings do
      resources :counting_signups, only: %i[index create destroy]
      resources :counting_areas, only: %i[index show]

      resources :area_assignments,
        only: %i[index new create edit update destroy] do
        collection { get :user }
      end

      resources :countees, only: %i[index new create destroy]

      get "results/counting_area",
        to: "results#counting_area",
        as: "counting_area_results"
      get "results/gender", to: "results#gender", as: "gender_results"
      get "results/age-group", to: "results#age_group", as: "age_group_results"
    end
  end
end

app/models/countee.rb
class Countee < ApplicationRecord
  belongs_to :counting
  belongs_to :counting_area

  belongs_to :gender, optional: true
  belongs_to :age_group, optional: true

  validate :created_while_counting_ongoing, on: :create

  validates :pet_count,
    numericality: {
      greater_than_or_equal_to: 0
    },
    allow_nil: true

  validates :gender_id, inclusion: {
    in: Gender.pluck(:id), message:  I18n.t("activerecord.errors.models.countee.attributes.gender_id.invalid")
  }, allow_blank: true

  validates :age_group_id, inclusion: {
    in: AgeGroup.pluck(:id), message:  I18n.t("activerecord.errors.models.countee.attributes.age_group_id.invalid")
  }, allow_blank: true

  private

  def created_while_counting_ongoing
    unless counting.ongoing?
      errors.add :base, :counting_not_ongoing, message:
        I18n.t(
          "activerecord.errors.models.countee.base.counting_not_ongoing"
        )
    end
  end
end

app/models/countee/validator.rb
# This is a custom validator that ensures that a countee can only be added while the associated counting is ongoing.
class CreatedAtValidator < ActiveModel::Validator
  def validate(countee)
    unless countee.counting.ongoing?
      countee.errors.add :created_at,
                         I18n.t(
                           'activerecord.errors.models.countee.attributes.created_at',
                         )
    end
  end
end

# This is a custom validator that ensures that the latitude and longitude of a countee find the associated district.
class DistrictValidator < ActiveModel::Validator
  def validate(countee)
    has_latitude_longitude =
      countee.latitude.present? && countee.longitude.present?

    containing_districts =
      District.contains_point?(countee.latitude.to_f, countee.longitude.to_f)

    unless has_latitude_longitude
      # First, clear out the default error for a non-existent, required association:
      countee.errors.delete(:district)

      # Instead, get more precise:
      countee.errors.add :district,
                         :no_lat_lon,
                         message:
                           I18n.t(
                             'activerecord.errors.models.countee.attributes.district.no_lat_lon',
                           )
    end

    if has_latitude_longitude && containing_districts.empty?
      # First, clear out the default error for a non-existent, required association:
      countee.errors.delete(:district)

      # Instead, get more precise:
      countee.errors.add :district,
                         :none_found,
                         message:
                           I18n.t(
                             'activerecord.errors.models.countee.attributes.district.none_found',
                           )
    end

    if has_latitude_longitude && containing_districts.length > 1
      # First, clear out the default error for a non-existent, required association:
      countee.errors.delete(:district)

      # Instead, get more precise:
      countee.errors.add :district,
                         :not_one,
                         message:
                           I18n.t(
                             'activerecord.errors.models.countee.attributes.district.not_one',
                           )
    end
  end
end

# Ensures gender exists (or is empty):
class GenderValidator < ActiveModel::Validator
  def validate(countee)
    unless countee.gender_id.blank? || Gender.exists?(countee.gender_id)
      countee.errors.add :gender_id,
                         I18n.t(
                           'activerecord.errors.models.countee.attributes.gender_id.invalid',
                         )
    end
  end
end

# Ensures age group exists (or is empty):
class AgeGroupValidator < ActiveModel::Validator
  def validate(countee)
    unless countee.age_group_id.blank? || AgeGroup.exists?(countee.age_group_id)
      countee.errors.add :age_group_id,
                         I18n.t(
                           'activerecord.errors.models.countee.attributes.age_group_id.invalid',
                         )
    end
  end
end

app/models/countee/validator/district_validator.rb
# This is a custom validator that ensures that the latitude and longitude of a countee find the associated district.
class Countee::Validator::DistrictValidator < ActiveModel::Validator
  def validate(countee)
    has_latitude_longitude =
      countee.latitude.present? && countee.longitude.present?

    containing_districts =
      District.contains_point?(countee.latitude.to_f, countee.longitude.to_f)

    unless has_latitude_longitude
      # First, clear out the default error for a non-existent, required association:
      countee.errors.delete(:district)

      # Instead, get more precise:
      countee.errors.add :district,
                         :no_lat_lon,
                         message:
                           I18n.t(
                             'activerecord.errors.models.countee.attributes.district.no_lat_lon',
                           )
    end

    if has_latitude_longitude && containing_districts.empty?
      # First, clear out the default error for a non-existent, required association:
      countee.errors.delete(:district)

      # Instead, get more precise:
      countee.errors.add :district,
                         :none_found,
                         message:
                           I18n.t(
                             'activerecord.errors.models.countee.attributes.district.none_found',
                           )
    end

    if has_latitude_longitude && containing_districts.length > 1
      # First, clear out the default error for a non-existent, required association:
      countee.errors.delete(:district)

      # Instead, get more precise:
      countee.errors.add :district,
                         :not_one,
                         message:
                           I18n.t(
                             'activerecord.errors.models.countee.attributes.district.not_one',
                           )
    end
  end
end

app/controllers/countees_controller.rb
require "csv"

class CounteesController < ApplicationController
  before_action :authenticate_admin!, only: %i[index destroy]
  before_action :authenticate_user!, only: %i[new create]

  before_action :set_counting
  before_action :set_countee, only: %i[destroy]

  def index
    respond_to do |format|
      format.html do
        @pagy, @countees = pagy(@counting.countees.order("created_at DESC"))
      end
      format.csv do
        @countees = @counting.countees.all

        response.headers["Content-Type"] = "text/csv"
        response.headers["Content-Disposition"] =
          "attachment; filename=counting-#{@counting.id}_countees.csv"
      end
    end
  end

  def new
    @countee = @counting.countees.build

    @area_assignment =
      current_user
        .counting_signups
        .find_by(counting: @counting)
        .area_assignments
        .find_by(counting_area_id: params[:counting_area_id])

    @countee.counting_area_id = @area_assignment&.counting_area_id
  end

  def create
    @countee = @counting.countees.build(countee_params)

    respond_to do |format|
      if @countee.save
        flash.now.notice = I18n.t("countees.create.notice")
        format.turbo_stream

        format.html do
          redirect_to new_counting_countee_url(@counting),
            notice: I18n.t("countees.create.notice")
        end
      else
        flash.now.alert = I18n.t("common.error")
        format.turbo_stream

        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @countee.destroy

    respond_to do |format|
      format.html do
        redirect_to counting_countees_url,
          notice: I18n.t("countees.destroy.notice")
      end
    end
  end

  private

  def set_counting
    @counting = Counting.find(params[:counting_id])
  end

  def set_countee
    @countee = @counting.countees.find(params[:id])
  end

  def countee_params
    params
      .require(:countee)
      .permit(
        :counting_id,
        :counting_area_id,
        :gender_id,
        :age_group_id,
        :pet_count
      )
  end
end

app/views/countees/_form.html.erb
<%= form_with(model: [@counting, countee], class: "h-full flex flex-col place-content-between", id: "countee_form", data: { "countee-target": "form" }) do |form| %>
  <div>

    <% unless action_name == 'edit' %>
      <%= form.hidden_field :counting_area_id,
                            data: { turbo_cache: false,
                                    countee_target: 'countingAreaIdInput'
                                  } %>
    <% end %>

    <div class="my-5">
      <%= form.label :gender_id, class: 'block font-bold text-base' %>

      <%= content_tag :div, class: class_names('mt-3', 'grid grid-cols-2 gap-2') do %>
        <%= form.label :gender_id_nil do %>
          <%= form.radio_button :gender_id,
              '',
              { id: 'countee_gender_id_nil', checked: 'checked', class: 'sr-only peer'}
          %>
          <%= content_tag(:span, '–', class: class_names('block w-full h-full', 'px-3 py-2', 'border border-blue-300 peer-checked:bg-white peer-checked:text-blue-800 peer-checked:font-bold', 'rounded-lg', 'text-center', 'peer-focus:border-yellow-500')) %>
        <% end %>
        <%= form.collection_radio_buttons :gender_id,
            Gender.order(:id),
            :id,
            :label do |b| b.label(class: 'block w-full h-full') { b.radio_button(class: 'sr-only peer') + content_tag(:span, b.text, class: class_names('block w-full h-full', 'px-3 py-2', 'border border-blue-300 peer-checked:bg-white peer-checked:text-blue-800 peer-checked:font-bold', 'rounded-lg', 'text-center', 'peer-focus:border-yellow-500')) } end %>
      <% end %>

      <% if countee.errors[:gender_id].any? %>
        <ul class="text-danger mt-1">
          <% countee.errors[:gender_id].each do |error_message| %>
          <li>
            <%= t('activerecord.attributes.countee.gender_id') %>&nbsp;<%= error_message %>
          </li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="my-5">
      <%= form.label :age_group_id, class: 'block font-bold text-base' %>

      <div class="mt-3 grid grid-cols-4 gap-2">
        <%= form.label :age_group_id_nil do %>
          <%= form.radio_button :age_group_id,
              '',
              { id: 'countee_age_group_id_nil', checked: 'checked', class: 'sr-only peer'}
          %>
          <%= content_tag(:span, '–', class: class_names('block w-full h-full', 'px-3 py-2', 'border border-blue-300 peer-checked:bg-white peer-checked:text-blue-800 peer-checked:font-bold', 'rounded-lg', 'text-center', 'peer-focus:border-yellow-500')) %>
        <% end %>
        <%= form.collection_radio_buttons :age_group_id,
            age_groups_with_label(AgeGroup.order(:id)),
            :id,
            :label do |b| b.label(class: 'block w-full h-full') { b.radio_button(class: 'sr-only peer') + content_tag(:span, b.text, class: class_names('block w-full h-full', 'px-3 py-2', 'border border-blue-300 peer-checked:bg-white peer-checked:text-blue-800 peer-checked:font-bold', 'rounded-lg', 'text-center', 'peer-focus:border-yellow-500')) } end
        %>
      </div>

      <% if countee.errors[:age_group_id].any? %>
        <ul class="text-danger mt-1">
          <% countee.errors[:age_group_id].each do |error_message| %>
          <li>
            <%= t('activerecord.attributes.countee.age_group_id') %>&nbsp;<%= error_message %>
          </li>
          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="my-5">
      <%= form.label :pet_count, class: 'block font-bold text-base' %>
      <%= form.number_field :pet_count, class: 'mt-3', data: { "turbo_cache": false } %>
      <% if countee.errors[:pet_count].any? %>
        <ul class="text-danger mt-1">
          <% countee.errors[:pet_count].each do |error_message| %>
          <li>
            <%= t('activerecord.attributes.countee.pet_count') %>&nbsp;<%= error_message %>
          </li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>

  <div class="block">
    <%= form.submit class: "button button-primary button-medium w-full" %>
  </div>
<% end %>

app/views/countees/all.csv.erb
<%= CSV.generate_line ['ID', t('activerecord.models.counting.one').capitalize, t('activerecord.models.counting_area.one'), t('activerecord.models.gender.one'), t('activerecord.models.age_group.one'), t('activerecord.attributes.countee.pet_count')] %>
<% @countees.each do |countee| %><%= CSV.generate_line([countee.id, countee.counting.title, countee.counting_area.name, countee.gender.present? ? countee.gender.label : nil, countee.age_group.present? ? age_group_label(countee.age_group.min_age, countee.age_group.max_age) : nil, countee.pet_count]) %><% end %>

app/views/countees/create.turbo_stream.erb
<% if @countee.persisted? %>
  <%= turbo_stream.replace 'countee_form', partial: 'countees/form', locals: { countee: Countee.new }  %>
<% else %>
  <%= turbo_stream.replace 'countee_form', partial: 'countees/form', locals: { countee: @countee }  %>
<% end %>

<%# We are replacing the flash here with the global_flash partial. %>
<%# It takes the currrent flash object as the only item to render. %>
<%# The current flash object is implicitly available, because we   %>
<%# have set flash.now in the CounteesController. %>
<%= turbo_stream.replace 'flash', partial: 'shared/global_flash', collection: [flash], as: :flash  %>

app/views/countees/index.csv.erb
<%= CSV.generate_line ['ID', t('activerecord.models.counting.one').capitalize, t('activerecord.models.counting_area.one'), t('activerecord.models.gender.one'), t('activerecord.models.age_group.one'), t('activerecord.attributes.countee.pet_count')] %>
<% @countees.each do |countee| %><%= CSV.generate_line([countee.id, countee.counting.title, countee.counting_area.name, countee.gender.present? ? countee.gender.label : nil, countee.age_group.present? ? age_group_label(countee.age_group.min_age, countee.age_group.max_age) : nil, countee.pet_count]) %><% end %>

app/views/countees/index.html.erb
<% content_for(:header_slot) {
    render ButtonComponent.new(scheme: :link, tag: :a, href: counting_path(@counting), class: 'p-0') do
      "← #{@counting.title}"
    end
  }
%>

<% content_for(:main_tag_classes) { 'p-5' } %>

<div>
  <div class="flex justify-between gap-2">
    <h1 class="text-2xl font-bold pb-2"><%= t('countees.index.title') %></h1>
    <% unless @counting.countees.empty? %>
      <%= render ButtonComponent.new(tag: :a, href: counting_countees_path(@counting, format: :csv)) do %>
        <%= t('countees.all.download') %>
      <% end %>
    <% end %>
  </div>
  <ul>
  <% @countees.each do |countee| %>
    <%= render(CounteeCardComponent.new(created_at: countee.created_at, counting_area: countee.counting_area.name, gender: countee.gender.present? && countee.gender.label, age_group: countee.age_group.present? && 
    age_group_label(countee.age_group.min_age, countee.age_group.max_age), pet_count: countee.pet_count.present? && countee.pet_count, class: 'mt-3')) %>
    <%= render(ButtonComponent.new(type: :submit, path: counting_countee_path(@counting, countee), scheme: :danger, method: :delete, form: { data: { turbo_confirm: t('countees.destroy.are_you_sure') } }, additional_classes: 'mt-3')) do %>
      <%= t('countees.destroy.title') %>
    <% end %>
  <% end %>
  </ul>
  <% if @pagy.pages > 1 %>
    <div class="mt-8">
      <%== pagy_nav(@pagy) %>
    </div>
  <% end %>
</div>

app/views/countees/new.html.erb
<% content_for(:header_slot) {
    render ButtonComponent.new(scheme: :link, tag: :a, href: counting_path(@counting), class: 'p-0') do
      "← #{@counting.title}"
    end
  }
%>

<div
  data-controller="countee"
  data-countee-maptiler-key-value="<%= Rails.application.credentials.publicly_visible_maptiler_key %>"
  class="w-full grid grid-rows-[200px_3fr] pb-8"
>
  <div
    id="map"
    data-turbo-permanent
    class="w-full h-full bg-blue-300"
  >
  </div>

  <div class="w-full h-full px-5 py-5">
    <h1 class="text-lg font-bold text-blue-200"><%= t('countees.new.title') %></h1>
    <div>
      <%= turbo_frame_tag 'user_area_assignments', src: user_counting_area_assignments_path(@counting, params: { counting_area_id: @area_assignment&.counting_area_id }) %>
    </div>
    <%= render "form", countee: @countee %>
  </div>
</div>