config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"

  # Lookbook has to be mounted before `get '/:locale'`, otherwise the router will treat 'lookbook' as a locale and throw an error
  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  # Brings the sole locale route to the homepage
  get "/:locale" => "home#index", :as => "locale_root"

  scope "(:locale)", locale: /en|de/ do
    devise_for :users,
      path: "users",
      path_names: {
        sign_in: "login",
        sign_out: "logout",
        sign_up: "register"
      },
      controllers: {
        sessions: "users/sessions",
        registrations: "users/registrations"
      }
    get "profile" => "profile#show", :as => "profile"

    resources :countings do
      resources :counting_signups, only: %i[index create destroy]
      resources :counting_areas, only: %i[index show]

      resources :area_assignments,
        only: %i[index new create edit update destroy] do
        collection { get :user }
      end

      resources :countees, only: %i[index new create destroy]

      get "results/counting_area",
        to: "results#counting_area",
        as: "counting_area_results"
      get "results/gender", to: "results#gender", as: "gender_results"
      get "results/age-group", to: "results#age_group", as: "age_group_results"
    end
  end
end

app/models/counting.rb
class Counting < ApplicationRecord
  has_rich_text :description_long

  validates :title, :starts_at, :ends_at, presence: true
  validates :ends_at,
    comparison: {
      greater_than: :starts_at
    },
    unless: -> { starts_at.blank? }

  belongs_to :user

  has_many :counting_signups, dependent: :destroy
  has_many :counting_areas, dependent: :destroy

  has_many :countees, dependent: :destroy

  scope :closest_first, -> { order("starts_at ASC") }
  scope :past, -> { where("ends_at < ?", Time.now) }
  scope :upcoming, -> { where("ends_at > ?", Time.now) }

  def ongoing?
    Time.now.between? starts_at, ends_at
  end

  def signups_allowed?
    Time.now.before? starts_at - 7.days
  end

  def area_assignments_allowed?
    !signups_allowed? && Time.now.before?(starts_at) && !ongoing?
  end
end

app/controllers/countings_controller.rb
class CountingsController < ApplicationController
  before_action :authenticate_admin!, only: %i[new create edit update destroy]
  before_action :set_counting, only: %i[show edit update destroy]

  def index
    @countings =
      if params[:status].present? && counting_status == "past"
        Counting.past.closest_first
      else
        Counting.upcoming.closest_first
      end
    @counting_status = counting_status
  end

  def show
  end

  def new
    @counting = Counting.new
  end

  def edit
  end

  def create
    @counting = Counting.new(counting_params)
    @counting.user_id = @current_user.id

    respond_to do |format|
      if @counting.save
        format.html do
          redirect_to counting_url(@counting),
            notice: I18n.t("countings.create.notice")
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @counting.update(counting_params)
        format.html do
          redirect_to counting_url(@counting),
            notice: I18n.t("countings.update.notice")
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @counting.destroy

    respond_to do |format|
      format.html do
        redirect_to countings_url, notice: I18n.t("countings.destroy.notice")
      end
    end
  end

  private

  def set_counting
    @counting = Counting.find(params[:id])
  end

  def counting_params
    params
      .require(:counting)
      .permit(
        :title,
        :description_short,
        :description_long,
        :starts_at,
        :ends_at
      )
  end

  def counting_status
    params[:status].presence_in(%w[upcoming past]) || "upcoming"
  end
end

app/helpers/countings_helper.rb
module CountingsHelper
  def filter_by(name, status, **options)
    render(
      ButtonComponent.new(
        scheme: :link,
        tag: :a,
        href: request.params.merge(status: status),
        class: "underline inline px-0",
        **options
      )
    ) { name }
  end
end

app/views/countings/_counting.html.erb
<%= tag.div id: dom_id(counting) do %>
  <article>
    <%= render(Counting::HeaderComponent.new(title: counting.title, starts_at: counting.starts_at, ends_at: counting.ends_at)) do %>
    <% end %>

    <% if current_user && counting.signups_allowed? %>
      <div class="mt-4 flex gap-2 justify-end items-center">
        <% if counting.counting_signups.find_by(user_id: current_user.id) %>
          <p class="text-sm text-yellow-400"><%= t('counting_signups.destroy.current_status') %></p>
          <%= render(ButtonComponent.new(path: counting_counting_signup_path(counting, counting.counting_signups.find_by(user: current_user.id)), type: :submit, method: :delete, scheme: :danger, form: { data: { turbo_confirm: t('counting_signups.destroy.are_you_sure') } })) do %>
            <%= t('counting_signups.destroy.title')%>
          <% end %>
        <% else %>
          <%= render(ButtonComponent.new(path: counting_counting_signups_path(counting), type: :submit, method: :post, scheme: :primary)) do %>
            <%= t('counting_signups.create.title')%>
          <% end %>
        <% end %>
      </div>
    <% end %>

    <% if user_signed_in? && counting.ongoing? && counting.counting_signups.find_by(user_id: current_user.id) %>
      <div class="mt-4">
        <%= render(ButtonComponent.new(tag: :a, href: new_counting_countee_path(counting), scheme: :primary, class: 'block w-full text-center')) do %>
          <%= t('countees.new.title') %>
        <% end %>
      </div>
    <% end %>

    <main class="pt-8">
      <%= counting.description_long %>
    </main>
  </article>

  <% if user_signed_in? and current_user.admin? %>
    <hr class="mt-8 mb-4 border border-dotted h-px">
    <h2><%= t('common.admin_area') %></h2>
    <div class="mt-4 flex gap-2 justify-between">
      <% if counting.area_assignments_allowed? %>
        <%= render(ButtonComponent.new(tag: :a, href: counting_counting_areas_path(counting), class: 'block w-full text-center')) do %>
          <%= t('activerecord.models.counting_area.other') %>
        <% end %>
      <% end %>
      <%= render(ButtonComponent.new(tag: :a, href: counting_countees_path(counting), class: 'block w-full text-center')) do %>
        <%= t('countees.index.title') %>
      <% end %>
    </div>
    <div class="mt-4 flex justify-center">
      <%= render(ButtonComponent.new(tag: :a, href: edit_counting_path(counting), scheme: :link, size: :small, class: 'px-0 underline')) do %>
        <%= t('countings.edit.explicitly') %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/countings/_counting_preview.html.erb
<%= tag.div id: dom_id(counting, :preview), class: "mt-6" do %>
  <%= link_to(counting, id: dom_id(counting), class: "group inline-block no-underline text-inherit") do %>
    <h2 class="text-2xl text-yellow-300 group-hover:text-yellow-200">
      <%= counting.title %>
    </h2>
  <% end %>

  <p class="mt-5 text-sm text-white">
    <time>
      <%= I18n.l(counting.starts_at, format: :long) %>
    </time> –
    <time>
      <%= I18n.l(counting.ends_at, format: :long) %>
    </time>
  </p>

  <p class="mt-2">
    <%= counting.description_short %>
  </p>
<% end %>

app/views/countings/_form.html.erb
<%= form_with(model: counting, class: "contents", id: 'counting_form') do |form| %>
  <div class="mt-5">
    <%= form.label :title %>
    <%= form.text_field :title %>

    <% if counting.errors[:title].any? %>
      <ul class="text-danger mt-1">
        <% counting.errors[:title].each do |error_message| %>
        <li>
          <%= t('activerecord.attributes.counting.title') %>&nbsp;<%= error_message %>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="mt-5">
    <%= form.label :description_short %>
    <%= form.text_area :description_short, rows: 4, class: "#{counting.errors[:description_short].any? ? 'border-danger' : ''}" %>
  </div>

  <div class="mt-5">
    <%= form.label :description_long %>
    <%= form.rich_text_area :description_long, class: "trix-editor #{counting.errors[:description_long].any? ? 'border-danger' : ''}" %>
  </div>

  <div class="mt-5">
    <%= form.label :starts_at %>
    <%= form.datetime_field :starts_at, class: "#{counting.errors[:starts_at].any? ? 'border-danger' : ''}" %>

    <% if counting.errors[:starts_at].any? %>
      <ul class="text-danger mt-1">
        <% counting.errors[:starts_at].each do |error_message| %>
        <li>
          <%= t('activerecord.attributes.counting.starts_at') %>&nbsp;<%= error_message %>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :ends_at %>
    <%= form.datetime_field :ends_at, class: "#{counting.errors[:ends_at].any? ? 'border-danger' : ''}" %>

    <% if counting.errors[:ends_at].any? %>
      <ul class="text-danger mt-1">
        <% counting.errors[:ends_at].each do |error_message| %>
        <li>
          <%= t('activerecord.attributes.counting.ends_at') %>&nbsp;<%= error_message %>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="flex justify-end">
    <%= form.submit class: 'button button-primary button-medium' %>
  </div>
<% end %>

app/views/countings/edit.html.erb
<% content_for(:header_slot) {
    render ButtonComponent.new(scheme: :link, tag: :a, href: counting_path, class: 'p-0') do
      "← #{t('countings.cancel.title')}"
    end
  }
%>

<% content_for(:html_title) { t('countings.edit.title') + ' | ' + @counting.title } %>

<div class="mt-8 px-5">
  <h1><%= t('countings.edit.title') %></h1>

  <%= render "form", counting: @counting %>

  <%= render(ButtonComponent.new(type: :submit, path: counting_path(@counting), scheme: :danger, method: :delete, form: { data: { turbo_confirm: t('countings.destroy.are_you_sure') } })) do %>
    <%= t('countings.destroy.explicitly') %>
  <% end %>
</div>

app/views/countings/index.html.erb
<% content_for(:main_tag_classes) { 'p-5' } %>

<% title = @counting_status == 'past' ? t('countings.index.title.past') : t('countings.index.title.upcoming') %>

<% content_for(:html_title) { t('countings.index.title.default') } %>

<div class="h-full flex flex-col justify-between">
  <div>
    <h1 class="text-lg font-bold"><%= title %></h1>
    <div id="countings" class="mt-6">
      <%= render partial: "counting_preview", collection: @countings, as: :counting %>
    </div>
  </div>

  <div class="border-t border-blue-500 pt-4 grid grid grid-cols-2 gap-2">
    <% if @counting_status == 'past' %>
      <%= filter_by t('countings.index.title.upcoming'), 'upcoming' %>
    <% else %>
      <%= filter_by t('countings.index.title.past'), 'past' %>
    <% end %>

    <% if user_signed_in? and current_user.admin? %>
      <%= render(ButtonComponent.new(scheme: :link, tag: :a, href: new_counting_path, class: 'underline inline px-0')) do %>
        <%= t('countings.new.title') %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/countings/new.html.erb
<% content_for(:html_title) { t('countings.new.title') } %>

<div class="mt-4 px-5">
  <h1 class=""><%= t('countings.new.title') %></h1>

  <%= render "form", counting: @counting %>

  <%= render(ButtonComponent.new(tag: :a, href: countings_path)) do %>
    <%= t('countings.back.title') %>
  <% end %>
</div>

app/views/countings/show.html.erb
<% content_for(:html_title) { @counting.title } %>

<% content_for(:header_slot) {
    render ButtonComponent.new(scheme: :link, tag: :a, href: countings_path, class: 'p-0') do
      "← #{t('countings.index.title.default')}"
    end
  }
%>

<% content_for(:main_tag_classes) { 'p-5' } %>

<%= render @counting %>