config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "home#index"

  # Lookbook has to be mounted before `get '/:locale'`, otherwise the router will treat 'lookbook' as a locale and throw an error
  mount Lookbook::Engine, at: "/lookbook" if Rails.env.development?

  # Brings the sole locale route to the homepage
  get "/:locale" => "home#index", :as => "locale_root"

  scope "(:locale)", locale: /en|de/ do
    devise_for :users,
      path: "users",
      path_names: {
        sign_in: "login",
        sign_out: "logout",
        sign_up: "register"
      },
      controllers: {
        sessions: "users/sessions",
        registrations: "users/registrations"
      }
    get "profile" => "profile#show", :as => "profile"

    resources :countings do
      resources :counting_signups, only: %i[index create destroy]
      resources :counting_areas, only: %i[index show]

      resources :area_assignments,
        only: %i[index new create edit update destroy] do
        collection { get :user }
      end

      resources :countees, only: %i[index new create destroy]

      get "results/counting_area",
        to: "results#counting_area",
        as: "counting_area_results"
      get "results/gender", to: "results#gender", as: "gender_results"
      get "results/age-group", to: "results#age_group", as: "age_group_results"
    end
  end
end

app/models/counting_area.rb
class CountingArea < ApplicationRecord
  validates :geometry, presence: true

  belongs_to :counting

  has_one :area_assignment, dependent: :destroy
end

app/controllers/counting_areas_controller.rb
class CountingAreasController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin!, except: %i[show]

  before_action :set_counting
  before_action :set_counting_areas, only: %i[index]
  before_action :set_counting_signups, only: %i[index]
  before_action :set_counting_area, only: %i[show]

  def index
    respond_to do |format|
      format.json do
        # Quoting the counting ID prevents SQL injections into the heredoc down below:
        quoted_counting_id = ActiveRecord::Base.connection.quote(@counting.id)

        # Heredoc of raw SQL that builds and generates GeoJSON representation:
        query_for_geojson_output = <<~SQL
          SELECT
            json_build_object(
              'type', 'FeatureCollection',
              'features', json_agg(ST_AsGeoJSON(temp_counting_areas.*)::json)
            )
            FROM
            (
              -- We use a subquery to not have the irrelevant columns as output:
              SELECT id, name, geometry
              FROM counting_areas
              WHERE counting_areas.counting_id = #{quoted_counting_id}
            ) AS temp_counting_areas;
        SQL

        # Returns all rows (in this case just one) as a hash:
        query_result =
          ActiveRecord::Base.connection.execute(query_for_geojson_output)

        # For some reason the json_build_object key is present in the output,
        # that's why we have to access its value which is the actual GeoJSON structure:
        render json: query_result.first["json_build_object"]
      end

      format.html do
      end
    end
  end

  def show
    respond_to do |format|
      format.json do
        # Quoting the ID prevents SQL injections into the heredoc down below:
        quoted_area_id = ActiveRecord::Base.connection.quote(params[:id])

        # Heredoc of raw SQL that builds and generates GeoJSON representation:
        query_for_geojson_output = <<~SQL
          SELECT ST_AsGeoJSON(temp_counting_area.*)
            FROM
            (
              -- We use a subquery to not have the irrelevant columns as output:
              SELECT id, name, geometry
              FROM counting_areas
              WHERE counting_areas.id = #{quoted_area_id}
              LIMIT 1
            ) AS temp_counting_area;
        SQL

        # Returns all rows (in this case just one) as a hash:
        query_result =
          ActiveRecord::Base.connection.execute(query_for_geojson_output)

        # For some reason the st_asgeojson key is present in the output,
        # that's why we have to access its value which is the actual GeoJSON structure:
        render json: query_result.first["st_asgeojson"]
      end

      format.html do
      end
    end
  end

  private

  def set_counting
    @counting = Counting.find(params[:counting_id])
  end

  def set_counting_areas
    @counting_areas = @counting.counting_areas

    @unassigned_counting_areas = @counting_areas.where.missing(:area_assignment)

    # For the assignment form in the view, we only need minimal information for the select options:
    @minimal_unassigned_counting_areas =
      @unassigned_counting_areas.map { |area| [area.name, area.id] }
  end

  # Retrieves all counting signups for the associated counting:
  def set_counting_signups
    @counting_signups = @counting.counting_signups

    # For the assignment form in the view, we only need minimal information for the select options:
    @minimal_counting_signups =
      @counting_signups.map { |signup| [signup.user.email, signup.id] }
  end

  def set_counting_area
    @counting_area = CountingArea.find(params[:id])
  end
end

app/views/counting_areas/index.html.erb
<% content_for(:header_slot) {
    render ButtonComponent.new(scheme: :link, tag: :a, href: counting_path(@counting), class: 'p-0') do
      "← #{@counting.title}"
    end
  }
%>

<div
  class="w-full h-full grid grid-cols-[5fr_3fr]"
  data-controller="area-assignments"
  data-area-assignments-style-url-value="https://api.maptiler.com/maps/cef2fea6-7018-4908-ad16-3a03fab46447/style.json?key=<%= Rails.application.credentials.publicly_visible_maptiler_key %>"
  data-area-assignments-center-value="13.404954,52.520008"
  data-area-assignments-zoom-value="11"
  data-area-assignmentsarea-assignments-marker-center-value="13.404954,52.520008"
  data-area-assignments-areas-geojson-path-value="<%= counting_counting_areas_path(@counting, format: :json) %>"
  data-area-assignments-assignments-path-value="<%= counting_area_assignments_path(@counting) %>"
  data-turbo-cache="false"
>
  <div class="h-full">
    <%= render HiddenComponent.new(id: 'area-assignment-activity') %>
    <div data-area-assignments-target="mapContainer" class="w-full h-full"></div>
  </div>
  <div class="p-5">
    <div class="mb-5">
      <h1 class="font-bold text-4xl">
        <%= t('activerecord.models.counting_area.other') %>
      </h1>
      <p class="mt-2">
        <%= t('.assigned_html',
                assigned_count: @counting_areas.size - @unassigned_counting_areas.size,
                total_count: @counting_areas.size)%>
      </p>
    </div>
    <%= turbo_frame_tag 'area_assignments_interactions', src: new_counting_area_assignment_path(@counting, counting_area_id: ''), data: { area_assignments_target: 'areaAssignmentForm' } %>
  </div>
</div>

app/views/counting_areas/show.html.erb
<%= turbo_frame_tag 'active_counting_area' do %>
  <div
    data-countee-target="area"
    data-area-path="<%= counting_counting_area_path(@counting,
                                                    @counting_area,
                                                    format: :json
                                                    ) %>"
    data-area-id="<%= @counting_area.id %>"
  >
    <%= @counting_area.name %>
  </div>
<% end %>